### ISSUE TITLE
Cannot build using libuhd 4.1.0.5

### ISSUE THREAD

**Issue by centowen** [samcrow/uhd-rust#6]
It seems like `uhd_usrp_enumerate_registers` no longer exists. If I remove the `enumerate_registers` function from usrp.rs everything appears to work. I do not know enough about uhd to know how to replace this call, or if this method is important.

If you want I can make a pull request to remove the function, but I do not know if anyone is depending on it.

**Comment by samcrow** [comment]
It looks like they removed uhd_usrp_enumerate_registers in UHD 4.0 with these two commits:
https://github.com/EttusResearch/uhd/commit/23f4f8cf4ea72d59740afcb5663e4541f93e821a
https://github.com/EttusResearch/uhd/commit/e115e046eca7b7485edb59abe794b24290195c75

Yes, please make a pull request to remove that.
